# Generated by Django 5.2.10 on 2026-01-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('url_to_image', models.URLField(blank=True, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'source_name', 'country', 'published_at'], name='news_articl_categor_83c4a5_idx')],
            },
        ),
    ]
