# Generated by Django 5.2.10 on 2026-01-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='news_articl_categor_83c4a5_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source_name', 'published_at'], name='news_articl_source__79ae7e_idx'),
        ),
    ]
