# Generated by Django 5.2.10 on 2026-01-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_article_news_articl_categor_83c4a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
