# Generated by Django 5.2.10 on 2026-01-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='news_articl_source__79ae7e_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_name',
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.source'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', 'published_at', 'author'], name='news_articl_source__484125_idx'),
        ),
    ]
