# Generated by Django 5.2.10 on 2026-01-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_source_remove_article_news_articl_source__79ae7e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
