# Generated by Django 5.2.10 on 2026-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options_alter_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='article',
            table='news_article_partitioned',
        ),
    ]
